#!/bin/sh
#
# (c) CENA 2004
# 
#

jar=/usr/share/java/ivy.jar 
re=/usr/share/java/regexp.jar
go=/usr/share/java/gnu-getopt.jar 
#jar=../lib/ivy-java-1.2.6.jar
bus=

if [ "$IVYBUS" ]; then
  bus="-DIVYBUS=${IVYBUS}"
fi

java -classpath ${jar}:${re}:${go} $bus fr.dgac.ivy.tools.Probe "$@"
